import './globals.css'
import  { Metadata } from 'next'
import TopBar from "./components/TopBar"
import Header from "./components/Header/index"
import Footer from './components/footer'
type props={
  children:React.ReactNode
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({children}:props) {
  return (
    <html lang="en">
      <body className='flex flex-col items-center '>
        <TopBar/>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
